routes/web.php
<?php

use App\Http\Controllers\ItemController;
use App\Http\Controllers\OrderController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/
Route::get('/', [OrderController::class, 'create'])->name('boilerplate.orders.create');
Route::post('/orders/create', [OrderController::class, 'store'])->name('boilerplate.orders.store');
Route::group([
    'domain' => config('boilerplate.app.domain', ''),
    'middleware' => ['web', 'boilerplate.locale'],
    'as' => 'boilerplate.',
], function () {
    // Admin routes
    Route::group(['middleware' => ['role:admin']], function () {
        Route::get('items', [ItemController::class, 'index'])->name('items.index');
        Route::post('items', [ItemController::class, 'store'])->name('items.store');
        Route::get('items/create', [ItemController::class, 'create'])->name('items.create');
        Route::get('items/{item}/edit', [ItemController::class, 'edit'])->name('items.edit');
        Route::put('items/{item}/update', [ItemController::class, 'update'])->name('items.update');
        Route::delete('items/{item}/destroy', [ItemController::class, 'destroy'])->name('items.destroy');

        Route::get('orders', [OrderController::class, 'index'])->name('orders.index');
        Route::get('orders/{order}/edit', [OrderController::class, 'edit'])->name('orders.edit');
        Route::delete('orders/{order}/destroy', [OrderController::class, 'destroy'])->name('orders.destroy');
    });

});

app/Models/Item.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Item extends Model
{
    use HasFactory;
    protected $guarded = [];

}

app/Http/Controllers/ItemController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\itemRequest;
use App\Models\Item;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\File;

class ItemController extends Controller
{

    public function index()
    {
        return view('items.list');
    }


    public function create()
    {
        return view('items.create');
    }


    public function store(itemRequest $request)
    {
        $item = Item::create([
            "title" => $request->title,
            "description" => $request->description,
            "price" => $request->price,
            "stock" => $request->stock,
        ]);
        $item->image = $request->image->storeAs('public/items/' . $item->id . '_item', $item->id . '_item_' . $request->image->getClientOriginalName());
        $item->image = str_replace('public/', 'storage/', $item->image);
        $item->save();


        return redirect()->route('boilerplate.items.edit', $item)
            ->with('growl', [__('boilerplate::items.successadd'), 'success']);
    }




    public function edit(Item $item)
    {
        return view('items.edit', [
            'item' => $item,
        ]);
    }


    public function update(Request $request, Item $item)
    {
        $this->validate($request, [
            'title' => 'required|unique:items,title,' . $item->id,
            'description' => 'required|string',
            'price' => 'required|numeric|regex:/^\d+(\.\d+)?$/',
            'stock' => 'required|integer',
        ]);
        if (isset($request->image)) {
            $this->validate($request, [
                'image' => 'required|image|mimes:jpeg,png,gif',
            ]);
            $oldImagePath = $item->image;
            if (File::exists($oldImagePath)) {
                File::delete($oldImagePath);
            }
            $item->image = $request->image->storeAs('public/items/' . $item->id . '_item', $item->id . '_item_' . $request->image->getClientOriginalName());
            $item->image = str_replace('public/', 'storage/', $item->image);
            $item->save();
        }


        $item->update([
            'title' => $request->title,
            "description" => $request->description,
            "price" => $request->price,
            "stock" => $request->stock,
        ]);

        return redirect()->route('boilerplate.items.edit', $item)
            ->with('growl', [__('boilerplate::items.successmod'), 'success']);
    }


    public function destroy(Item $item)
    {
        $directoryPath = storage_path('app/public/items/' . $item->id . '_item');

        if (File::exists($directoryPath)) {
            File::deleteDirectory($directoryPath);
        }
        return response()->json(['success' => $item->delete() ?? false]);
    }
}

resources/views/items/create.blade.php
@extends('boilerplate::layout.index', [
'title' => __('boilerplate::items.title'),
'subtitle' => __('boilerplate::items.create.title'),
'breadcrumb' => [
__('boilerplate::items.title') => 'boilerplate.items.index',
__('boilerplate::items.create.title')
]
])

@section('content')
<form method="POST" action="{{ route('boilerplate.items.store') }}" autocomplete="off" enctype="multipart/form-data">
    @csrf
    <div class="row">
        <div class="col-12 pb-3">
            <a href="{{ route("boilerplate.items.index") }}" class="btn btn-default" data-toggle="tooltip" title="@lang('boilerplate::items.returntolist')">
                <span class="far fa-arrow-alt-circle-left text-muted"></span>
            </a>
            <span class="btn-group float-right">
                <button type="submit" class="btn btn-primary">
                    @lang('boilerplate::items.save')
                </button>
            </span>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-12">
            @component('boilerplate::card', ['title' => 'boilerplate::items.informations'])
            @component('boilerplate::input', ['name' => 'title', 'label' => 'boilerplate::items.name'])@endcomponent
            @component('boilerplate::input', ['name' => 'description', 'label' => 'boilerplate::items.description'])@endcomponent
            @component('boilerplate::input', ['name' => 'price', 'label' => 'boilerplate::items.price'])@endcomponent
            @component('boilerplate::input', ['name' => 'stock', 'label' => 'boilerplate::items.stock'])@endcomponent
            <label for="avatar"> @lang('boilerplate::items.image')</label><br>
            @error('image')
            <div class="error-bubble">
                <div>{{$message}}</div>
            </div>
            @enderror
            <input type="file" id="avatar" name="image" accept="image/png, image/jpeg" />
            @endcomponent
        </div>
    </div>
</form>
@endsection

resources/views/items/edit.blade.php
@extends('boilerplate::layout.index', [
'title' => __('boilerplate::items.title'),
'subtitle' => __('boilerplate::items.edit.title'),
'breadcrumb' => [
__('boilerplate::items.title') => 'boilerplate.items.index',
__('boilerplate::items.edit.title')
]
])
<style>
    .delete-icon {
        color: red;
        cursor: pointer;
        position: absolute;
        top: 5px;
        right: 5px;
    }

    .image-container {
        border: 1px solid #ccc;
        padding: 5px;
        position: relative;
        display: inline-block;
        width: 200px; /* Adjust the width if needed */
    }

    #image {
        width: 100%;
        height: auto;
    }
</style>
@section('content')
<form action="{{ route('boilerplate.items.update', $item->id) }}" method="POST" autocomplete="off" enctype="multipart/form-data">
    @csrf
    @method('PUT')
    <div class="row">
        <div class="col-12 pb-3">
            <a href="{{ route("boilerplate.items.index") }}" class="btn btn-default" data-toggle="tooltip" title="@lang('boilerplate::items.returntolist')">
                <span class="far fa-arrow-alt-circle-left text-muted"></span>
            </a>
            <span class="btn-group float-right">
                <button type="submit" class="btn btn-primary">
                    @lang('boilerplate::items.save')
                </button>
            </span>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-12">
            @component('boilerplate::card', ['title' => 'boilerplate::items.informations'])
            @component('boilerplate::input', ['name' => 'title', 'label' => 'boilerplate::items.name','value'=> $item->title])@endcomponent
            @component('boilerplate::input', ['name' => 'description', 'label' => 'boilerplate::items.description','value'=> $item->description])@endcomponent
            @component('boilerplate::input', ['name' => 'price', 'label' => 'boilerplate::items.price','value'=> $item->price])@endcomponent
            @component('boilerplate::input', ['name' => 'stock', 'label' => 'boilerplate::items.stock','value'=> $item->stock])@endcomponent
            <label for="avatar"> @lang('boilerplate::items.image')</label><br>
            @if($item->image)
            <div class="image-container" id="image-container">
                <img id="image" src="{{ asset($item->image) }}" width="200">
                <span class="delete-icon" onclick="deleteImage(event)">❌</span>
                <input type="hidden" id="imageInput" name="file" value="{{ $item->image }}">
            </div>
            @error('image')
            <div class="error-bubble">
                <div>{{$message}}</div>
            </div>
            @enderror
            <input type="file" id="fileInput" name="image" accept="image/png, image/jpeg" style="display: none;">
            @endif
            @endcomponent
        </div>

    </div>
</form>

<script>
    function deleteImage(event) {
        event.preventDefault(); // Prevent form submission

        var imageContainer = document.getElementById('image-container');
        var deleteButton = document.getElementById('deleteButton');
        var fileInput = document.getElementById('fileInput');
        var imageInput = document.getElementById('imageInput');

        if (confirm('Are you sure you want to delete this image?')) {
            // Remove the image container
            imageContainer.parentNode.removeChild(imageContainer);

            // Show the file input field if it exists
            if (fileInput) {
                fileInput.style.display = 'block';
            }

            // Clear the value of the hidden input field
            imageInput.value = '';

            // Hide the delete button if it exists
            if (deleteButton) {
                deleteButton.style.display = 'none';
            }

            // Optionally, you can submit the form or perform other actions here
        }
    }
</script>

@endsection

resources/views/items/list.blade.php
@extends('boilerplate::layout.index', [
'title' => __('boilerplate::items.title'),
'subtitle' => __('boilerplate::items.list.title'),
'breadcrumb' => [
__('boilerplate::items.list.title') => 'boilerplate.items.index'
]
])

@section('content')
<div class="row">
    <div class="col-12 mbl">
        <span class="float-right pb-3">
            <a href="{{ route("boilerplate.items.create") }}" class="btn btn-primary">
                @lang('boilerplate::items.create.title')
            </a>
        </span>
    </div>
</div>

@component('boilerplate::card')

@component('boilerplate::datatable', ['name' => 'items']) @endcomponent

@endcomponent
@endsection

@push('css')
<style>
    .img-circle {
        border: 1px solid #CCC
    }
</style>
@endpush